"""
    Spyderbat API UI & Public APIs

    Restful APIs for use by UI & customers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sbapi
from sbapi.model.expr import Expr
from sbapi.model.rstore_causal_query import RstoreCausalQuery
globals()['Expr'] = Expr
globals()['RstoreCausalQuery'] = RstoreCausalQuery
from sbapi.model.metrics_data_query_input import MetricsDataQueryInput


class TestMetricsDataQueryInput(unittest.TestCase):
    """MetricsDataQueryInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetricsDataQueryInput(self):
        """Test MetricsDataQueryInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetricsDataQueryInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
