"""
    Spyderbat API UI & Public APIs

    Restful APIs for use by UI & customers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sbapi
from sbapi.model.rbac_action import RBACAction
globals()['RBACAction'] = RBACAction
from sbapi.model.api_rbac_actions import ApiRBACActions


class TestApiRBACActions(unittest.TestCase):
    """ApiRBACActions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiRBACActions(self):
        """Test ApiRBACActions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiRBACActions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
