"""
    Spyderbat API UI & Public APIs

    Restful APIs for use by UI & customers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: apisupport@spyderbat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spyderbat_api
from spyderbat_api.model.org_invite_users_input import OrgInviteUsersInput


class TestOrgInviteUsersInput(unittest.TestCase):
    """OrgInviteUsersInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgInviteUsersInput(self):
        """Test OrgInviteUsersInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrgInviteUsersInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
