"""
    Spyderbat API UI & Public APIs

    Restful APIs for use by UI & customers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: apisupport@spyderbat.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spyderbat_api
from spyderbat_api.model.orc_api_bat_work import OrcApiBatWork
globals()['OrcApiBatWork'] = OrcApiBatWork
from spyderbat_api.model.orc_api_agent_work import OrcApiAgentWork


class TestOrcApiAgentWork(unittest.TestCase):
    """OrcApiAgentWork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrcApiAgentWork(self):
        """Test OrcApiAgentWork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrcApiAgentWork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
