"""
    Spyderbat API UI & Public APIs

    Restful APIs for use by UI & customers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sbapi
from sbapi.model.orc_api_runtime_details import OrcApiRuntimeDetails
globals()['OrcApiRuntimeDetails'] = OrcApiRuntimeDetails
from sbapi.model.src_create_input import SrcCreateInput


class TestSrcCreateInput(unittest.TestCase):
    """SrcCreateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSrcCreateInput(self):
        """Test SrcCreateInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SrcCreateInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
