"""
    Spyderbat API UI & Public APIs

    Restful APIs for use by UI & customers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sbapi
from sbapi.model.session_org_type_max_limit import SessionOrgTypeMaxLimit


class TestSessionOrgTypeMaxLimit(unittest.TestCase):
    """SessionOrgTypeMaxLimit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionOrgTypeMaxLimit(self):
        """Test SessionOrgTypeMaxLimit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionOrgTypeMaxLimit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
