/**
 * Spyderbat API UI & Public APIs
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DaoAgentConfig from './DaoAgentConfig';

/**
 * The AgentRegistrationUpdateInput model module.
 * @module model/AgentRegistrationUpdateInput
 * @version 1.0.0
 */
class AgentRegistrationUpdateInput {
    /**
     * Constructs a new <code>AgentRegistrationUpdateInput</code>.
     * @alias module:model/AgentRegistrationUpdateInput
     */
    constructor() { 
        
        AgentRegistrationUpdateInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AgentRegistrationUpdateInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgentRegistrationUpdateInput} obj Optional instance to populate.
     * @return {module:model/AgentRegistrationUpdateInput} The populated <code>AgentRegistrationUpdateInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgentRegistrationUpdateInput();

            if (data.hasOwnProperty('config')) {
                obj['config'] = DaoAgentConfig.constructFromObject(data['config']);
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('resource_name')) {
                obj['resource_name'] = ApiClient.convertToType(data['resource_name'], 'String');
            }
            if (data.hasOwnProperty('valid_from')) {
                obj['valid_from'] = ApiClient.convertToType(data['valid_from'], 'Date');
            }
            if (data.hasOwnProperty('valid_to')) {
                obj['valid_to'] = ApiClient.convertToType(data['valid_to'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DaoAgentConfig} config
 */
AgentRegistrationUpdateInput.prototype['config'] = undefined;

/**
 * The user UID of the user who created the agent registration
 * @member {String} created_by
 */
AgentRegistrationUpdateInput.prototype['created_by'] = undefined;

/**
 * Description of the agent registration
 * @member {String} description
 */
AgentRegistrationUpdateInput.prototype['description'] = undefined;

/**
 * Name of the agent registration
 * @member {String} name
 */
AgentRegistrationUpdateInput.prototype['name'] = undefined;

/**
 * Resource name used for RBAC
 * @member {String} resource_name
 */
AgentRegistrationUpdateInput.prototype['resource_name'] = undefined;

/**
 * Valid from date, the first date this object was valid
 * @member {Date} valid_from
 */
AgentRegistrationUpdateInput.prototype['valid_from'] = undefined;

/**
 * Valid to date, the date this object is valid to
 * @member {Date} valid_to
 */
AgentRegistrationUpdateInput.prototype['valid_to'] = undefined;






export default AgentRegistrationUpdateInput;

