/**
 * Spyderbat API UI & Public APIs
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiKeyUpdateInput model module.
 * @module model/ApiKeyUpdateInput
 * @version 1.0.0
 */
class ApiKeyUpdateInput {
    /**
     * Constructs a new <code>ApiKeyUpdateInput</code>.
     * @alias module:model/ApiKeyUpdateInput
     */
    constructor() { 
        
        ApiKeyUpdateInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiKeyUpdateInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiKeyUpdateInput} obj Optional instance to populate.
     * @return {module:model/ApiKeyUpdateInput} The populated <code>ApiKeyUpdateInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiKeyUpdateInput();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Description of the API key
 * @member {String} description
 */
ApiKeyUpdateInput.prototype['description'] = undefined;

/**
 * Is the key enabled or not
 * @member {Boolean} enabled
 */
ApiKeyUpdateInput.prototype['enabled'] = undefined;






export default ApiKeyUpdateInput;

