/**
 * Spyderbat API UI & Public APIs
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DaoPolicy from './DaoPolicy';

/**
 * The DaoPlan model module.
 * @module model/DaoPlan
 * @version 1.0.0
 */
class DaoPlan {
    /**
     * Constructs a new <code>DaoPlan</code>.
     * Plan
     * @alias module:model/DaoPlan
     */
    constructor() { 
        
        DaoPlan.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DaoPlan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DaoPlan} obj Optional instance to populate.
     * @return {module:model/DaoPlan} The populated <code>DaoPlan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DaoPlan();

            if (data.hasOwnProperty('policies')) {
                obj['policies'] = ApiClient.convertToType(data['policies'], [DaoPolicy]);
            }
        }
        return obj;
    }


}

/**
 * Policies for the plan
 * @member {Array.<module:model/DaoPolicy>} policies
 */
DaoPlan.prototype['policies'] = undefined;






export default DaoPlan;

