/**
 * Spyderbat API UI & Public APIs
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DaoOrgRoles from './DaoOrgRoles';

/**
 * The DaoSignupPolicy model module.
 * @module model/DaoSignupPolicy
 * @version 1.0.0
 */
class DaoSignupPolicy {
    /**
     * Constructs a new <code>DaoSignupPolicy</code>.
     * Signup policy
     * @alias module:model/DaoSignupPolicy
     */
    constructor() { 
        
        DaoSignupPolicy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DaoSignupPolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DaoSignupPolicy} obj Optional instance to populate.
     * @return {module:model/DaoSignupPolicy} The populated <code>DaoSignupPolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DaoSignupPolicy();

            if (data.hasOwnProperty('create_personal_org')) {
                obj['create_personal_org'] = ApiClient.convertToType(data['create_personal_org'], 'Boolean');
            }
            if (data.hasOwnProperty('default_org_roles')) {
                obj['default_org_roles'] = ApiClient.convertToType(data['default_org_roles'], [DaoOrgRoles]);
            }
            if (data.hasOwnProperty('requires_approval')) {
                obj['requires_approval'] = ApiClient.convertToType(data['requires_approval'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Create a personal org for the user
 * @member {Boolean} create_personal_org
 */
DaoSignupPolicy.prototype['create_personal_org'] = undefined;

/**
 * Default org roles for new orgs
 * @member {Array.<module:model/DaoOrgRoles>} default_org_roles
 */
DaoSignupPolicy.prototype['default_org_roles'] = undefined;

/**
 * Require admin approval for new orgs
 * @member {Boolean} requires_approval
 */
DaoSignupPolicy.prototype['requires_approval'] = undefined;






export default DaoSignupPolicy;

