/**
 * Spyderbat API UI & Public APIs
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Expr from './Expr';
import NotificationPolicyDestination from './NotificationPolicyDestination';

/**
 * The NotificationPolicyRoutesInner model module.
 * @module model/NotificationPolicyRoutesInner
 * @version 1.0.0
 */
class NotificationPolicyRoutesInner {
    /**
     * Constructs a new <code>NotificationPolicyRoutesInner</code>.
     * @alias module:model/NotificationPolicyRoutesInner
     */
    constructor() { 
        
        NotificationPolicyRoutesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NotificationPolicyRoutesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NotificationPolicyRoutesInner} obj Optional instance to populate.
     * @return {module:model/NotificationPolicyRoutesInner} The populated <code>NotificationPolicyRoutesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotificationPolicyRoutesInner();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('destination')) {
                obj['destination'] = NotificationPolicyDestination.constructFromObject(data['destination']);
            }
            if (data.hasOwnProperty('expr')) {
                obj['expr'] = Expr.constructFromObject(data['expr']);
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
        }
        return obj;
    }


}

/**
 * UI-supplied data
 * @member {Object} data
 */
NotificationPolicyRoutesInner.prototype['data'] = undefined;

/**
 * @member {String} description
 */
NotificationPolicyRoutesInner.prototype['description'] = undefined;

/**
 * @member {module:model/NotificationPolicyDestination} destination
 */
NotificationPolicyRoutesInner.prototype['destination'] = undefined;

/**
 * @member {module:model/Expr} expr
 */
NotificationPolicyRoutesInner.prototype['expr'] = undefined;

/**
 * One of the targets specified in `targets`
 * @member {String} target
 */
NotificationPolicyRoutesInner.prototype['target'] = undefined;






export default NotificationPolicyRoutesInner;

