/*
 * Spyderbat API UI & Public APIs
 *
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AgentSetOrgWorkInput {
    /// User defined tags
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "work", skip_serializing_if = "Option::is_none")]
    pub work: Option<Box<crate::models::OrcApiAgentWork>>,
}

impl AgentSetOrgWorkInput {
    pub fn new() -> AgentSetOrgWorkInput {
        AgentSetOrgWorkInput {
            tags: None,
            work: None,
        }
    }
}


