/*
 * Spyderbat API UI & Public APIs
 *
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Agent {
    /// Agent registration associated with the agent
    #[serde(rename = "agent_registration_uid", skip_serializing_if = "Option::is_none")]
    pub agent_registration_uid: Option<String>,
    /// Agent type
    #[serde(rename = "agent_type", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<String>,
    /// Description of the the purpose of the agent
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Agent OrgUID
    #[serde(rename = "org_uid", skip_serializing_if = "Option::is_none")]
    pub org_uid: Option<String>,
    /// Resource name used for RBAC
    #[serde(rename = "resource_name", skip_serializing_if = "Option::is_none")]
    pub resource_name: Option<String>,
    #[serde(rename = "resource_policy", skip_serializing_if = "Option::is_none")]
    pub resource_policy: Option<Box<crate::models::ResourcePolicy>>,
    /// Description of the runtime of the agent
    #[serde(rename = "runtime_description", skip_serializing_if = "Option::is_none")]
    pub runtime_description: Option<String>,
    #[serde(rename = "runtime_details", skip_serializing_if = "Option::is_none")]
    pub runtime_details: Option<Box<crate::models::OrcApiRuntimeDetails>>,
    /// Agent UID
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
    /// Valid from date, the first date this object was valid
    #[serde(rename = "valid_from", skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<String>,
    /// Valid to date, the date this object is valid to
    #[serde(rename = "valid_to", skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<String>,
}

impl Agent {
    pub fn new() -> Agent {
        Agent {
            agent_registration_uid: None,
            agent_type: None,
            description: None,
            org_uid: None,
            resource_name: None,
            resource_policy: None,
            runtime_description: None,
            runtime_details: None,
            uid: None,
            valid_from: None,
            valid_to: None,
        }
    }
}


