/*
 * Spyderbat API UI & Public APIs
 *
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DaoOrgUser {
    /// The email address of the user who belongs to this org
    #[serde(rename = "email")]
    pub email: String,
    /// The roles of the user who belongs to this org
    #[serde(rename = "roles")]
    pub roles: Vec<String>,
}

impl DaoOrgUser {
    pub fn new(email: String, roles: Vec<String>) -> DaoOrgUser {
        DaoOrgUser {
            email,
            roles,
        }
    }
}


