/*
 * Spyderbat API UI & Public APIs
 *
 * Restful APIs for use by UI & customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@spyderbat.com
 * Generated by: https://openapi-generator.tech
 */

/// RstreamTimeRange : returns true if the property is a time and is start<=time<end



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RstreamTimeRange {
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<f64>,
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<f64>,
}

impl RstreamTimeRange {
    /// returns true if the property is a time and is start<=time<end
    pub fn new() -> RstreamTimeRange {
        RstreamTimeRange {
            end_time: None,
            start_time: None,
        }
    }
}


