/*
Spyderbat API UI & Public APIs

Restful APIs for use by UI & customers.

API version: 1.0.0
Contact: apisupport@spyderbat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spyderbat_api

import (
	"encoding/json"
	"time"
)

// Source struct for Source
type Source struct {
	// User supplied description of the source
	Description *string `json:"description,omitempty"`
	LastData *time.Time `json:"last_data,omitempty"`
	// The end of the last chunk ingested from the agent
	LastIngestChunkEndTime *time.Time `json:"last_ingest_chunk_end_time,omitempty"`
	// The end of the last chunk stored from the agent
	LastStoredChunkEndTime *time.Time `json:"last_stored_chunk_end_time,omitempty"`
	// User supplied name of the source
	Name *string `json:"name,omitempty"`
	// The org this source is associated with
	OrgUid *string `json:"org_uid,omitempty"`
	// Resource name used for RBAC
	ResourceName *string `json:"resource_name,omitempty"`
	ResourcePolicy *ResourcePolicy `json:"resource_policy,omitempty"`
	// Description of the runtime of the source
	RuntimeDescription *string `json:"runtime_description,omitempty"`
	RuntimeDetails *OrcApiRuntimeDetails `json:"runtime_details,omitempty"`
	// User supplied tags
	Tags []string `json:"tags,omitempty"`
	// Type of source
	Type *string `json:"type,omitempty"`
	// The UID of the source
	Uid *string `json:"uid,omitempty"`
	// Valid from date, the first date this object was valid
	ValidFrom *time.Time `json:"valid_from,omitempty"`
	// Valid to date, the date this object is valid to
	ValidTo *time.Time `json:"valid_to,omitempty"`
}

// NewSource instantiates a new Source object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSource() *Source {
	this := Source{}
	return &this
}

// NewSourceWithDefaults instantiates a new Source object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceWithDefaults() *Source {
	this := Source{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Source) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Source) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Source) SetDescription(v string) {
	o.Description = &v
}

// GetLastData returns the LastData field value if set, zero value otherwise.
func (o *Source) GetLastData() time.Time {
	if o == nil || o.LastData == nil {
		var ret time.Time
		return ret
	}
	return *o.LastData
}

// GetLastDataOk returns a tuple with the LastData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetLastDataOk() (*time.Time, bool) {
	if o == nil || o.LastData == nil {
		return nil, false
	}
	return o.LastData, true
}

// HasLastData returns a boolean if a field has been set.
func (o *Source) HasLastData() bool {
	if o != nil && o.LastData != nil {
		return true
	}

	return false
}

// SetLastData gets a reference to the given time.Time and assigns it to the LastData field.
func (o *Source) SetLastData(v time.Time) {
	o.LastData = &v
}

// GetLastIngestChunkEndTime returns the LastIngestChunkEndTime field value if set, zero value otherwise.
func (o *Source) GetLastIngestChunkEndTime() time.Time {
	if o == nil || o.LastIngestChunkEndTime == nil {
		var ret time.Time
		return ret
	}
	return *o.LastIngestChunkEndTime
}

// GetLastIngestChunkEndTimeOk returns a tuple with the LastIngestChunkEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetLastIngestChunkEndTimeOk() (*time.Time, bool) {
	if o == nil || o.LastIngestChunkEndTime == nil {
		return nil, false
	}
	return o.LastIngestChunkEndTime, true
}

// HasLastIngestChunkEndTime returns a boolean if a field has been set.
func (o *Source) HasLastIngestChunkEndTime() bool {
	if o != nil && o.LastIngestChunkEndTime != nil {
		return true
	}

	return false
}

// SetLastIngestChunkEndTime gets a reference to the given time.Time and assigns it to the LastIngestChunkEndTime field.
func (o *Source) SetLastIngestChunkEndTime(v time.Time) {
	o.LastIngestChunkEndTime = &v
}

// GetLastStoredChunkEndTime returns the LastStoredChunkEndTime field value if set, zero value otherwise.
func (o *Source) GetLastStoredChunkEndTime() time.Time {
	if o == nil || o.LastStoredChunkEndTime == nil {
		var ret time.Time
		return ret
	}
	return *o.LastStoredChunkEndTime
}

// GetLastStoredChunkEndTimeOk returns a tuple with the LastStoredChunkEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetLastStoredChunkEndTimeOk() (*time.Time, bool) {
	if o == nil || o.LastStoredChunkEndTime == nil {
		return nil, false
	}
	return o.LastStoredChunkEndTime, true
}

// HasLastStoredChunkEndTime returns a boolean if a field has been set.
func (o *Source) HasLastStoredChunkEndTime() bool {
	if o != nil && o.LastStoredChunkEndTime != nil {
		return true
	}

	return false
}

// SetLastStoredChunkEndTime gets a reference to the given time.Time and assigns it to the LastStoredChunkEndTime field.
func (o *Source) SetLastStoredChunkEndTime(v time.Time) {
	o.LastStoredChunkEndTime = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Source) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Source) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Source) SetName(v string) {
	o.Name = &v
}

// GetOrgUid returns the OrgUid field value if set, zero value otherwise.
func (o *Source) GetOrgUid() string {
	if o == nil || o.OrgUid == nil {
		var ret string
		return ret
	}
	return *o.OrgUid
}

// GetOrgUidOk returns a tuple with the OrgUid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetOrgUidOk() (*string, bool) {
	if o == nil || o.OrgUid == nil {
		return nil, false
	}
	return o.OrgUid, true
}

// HasOrgUid returns a boolean if a field has been set.
func (o *Source) HasOrgUid() bool {
	if o != nil && o.OrgUid != nil {
		return true
	}

	return false
}

// SetOrgUid gets a reference to the given string and assigns it to the OrgUid field.
func (o *Source) SetOrgUid(v string) {
	o.OrgUid = &v
}

// GetResourceName returns the ResourceName field value if set, zero value otherwise.
func (o *Source) GetResourceName() string {
	if o == nil || o.ResourceName == nil {
		var ret string
		return ret
	}
	return *o.ResourceName
}

// GetResourceNameOk returns a tuple with the ResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetResourceNameOk() (*string, bool) {
	if o == nil || o.ResourceName == nil {
		return nil, false
	}
	return o.ResourceName, true
}

// HasResourceName returns a boolean if a field has been set.
func (o *Source) HasResourceName() bool {
	if o != nil && o.ResourceName != nil {
		return true
	}

	return false
}

// SetResourceName gets a reference to the given string and assigns it to the ResourceName field.
func (o *Source) SetResourceName(v string) {
	o.ResourceName = &v
}

// GetResourcePolicy returns the ResourcePolicy field value if set, zero value otherwise.
func (o *Source) GetResourcePolicy() ResourcePolicy {
	if o == nil || o.ResourcePolicy == nil {
		var ret ResourcePolicy
		return ret
	}
	return *o.ResourcePolicy
}

// GetResourcePolicyOk returns a tuple with the ResourcePolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetResourcePolicyOk() (*ResourcePolicy, bool) {
	if o == nil || o.ResourcePolicy == nil {
		return nil, false
	}
	return o.ResourcePolicy, true
}

// HasResourcePolicy returns a boolean if a field has been set.
func (o *Source) HasResourcePolicy() bool {
	if o != nil && o.ResourcePolicy != nil {
		return true
	}

	return false
}

// SetResourcePolicy gets a reference to the given ResourcePolicy and assigns it to the ResourcePolicy field.
func (o *Source) SetResourcePolicy(v ResourcePolicy) {
	o.ResourcePolicy = &v
}

// GetRuntimeDescription returns the RuntimeDescription field value if set, zero value otherwise.
func (o *Source) GetRuntimeDescription() string {
	if o == nil || o.RuntimeDescription == nil {
		var ret string
		return ret
	}
	return *o.RuntimeDescription
}

// GetRuntimeDescriptionOk returns a tuple with the RuntimeDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetRuntimeDescriptionOk() (*string, bool) {
	if o == nil || o.RuntimeDescription == nil {
		return nil, false
	}
	return o.RuntimeDescription, true
}

// HasRuntimeDescription returns a boolean if a field has been set.
func (o *Source) HasRuntimeDescription() bool {
	if o != nil && o.RuntimeDescription != nil {
		return true
	}

	return false
}

// SetRuntimeDescription gets a reference to the given string and assigns it to the RuntimeDescription field.
func (o *Source) SetRuntimeDescription(v string) {
	o.RuntimeDescription = &v
}

// GetRuntimeDetails returns the RuntimeDetails field value if set, zero value otherwise.
func (o *Source) GetRuntimeDetails() OrcApiRuntimeDetails {
	if o == nil || o.RuntimeDetails == nil {
		var ret OrcApiRuntimeDetails
		return ret
	}
	return *o.RuntimeDetails
}

// GetRuntimeDetailsOk returns a tuple with the RuntimeDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetRuntimeDetailsOk() (*OrcApiRuntimeDetails, bool) {
	if o == nil || o.RuntimeDetails == nil {
		return nil, false
	}
	return o.RuntimeDetails, true
}

// HasRuntimeDetails returns a boolean if a field has been set.
func (o *Source) HasRuntimeDetails() bool {
	if o != nil && o.RuntimeDetails != nil {
		return true
	}

	return false
}

// SetRuntimeDetails gets a reference to the given OrcApiRuntimeDetails and assigns it to the RuntimeDetails field.
func (o *Source) SetRuntimeDetails(v OrcApiRuntimeDetails) {
	o.RuntimeDetails = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Source) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetTagsOk() ([]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Source) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Source) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Source) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Source) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Source) SetType(v string) {
	o.Type = &v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *Source) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *Source) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *Source) SetUid(v string) {
	o.Uid = &v
}

// GetValidFrom returns the ValidFrom field value if set, zero value otherwise.
func (o *Source) GetValidFrom() time.Time {
	if o == nil || o.ValidFrom == nil {
		var ret time.Time
		return ret
	}
	return *o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetValidFromOk() (*time.Time, bool) {
	if o == nil || o.ValidFrom == nil {
		return nil, false
	}
	return o.ValidFrom, true
}

// HasValidFrom returns a boolean if a field has been set.
func (o *Source) HasValidFrom() bool {
	if o != nil && o.ValidFrom != nil {
		return true
	}

	return false
}

// SetValidFrom gets a reference to the given time.Time and assigns it to the ValidFrom field.
func (o *Source) SetValidFrom(v time.Time) {
	o.ValidFrom = &v
}

// GetValidTo returns the ValidTo field value if set, zero value otherwise.
func (o *Source) GetValidTo() time.Time {
	if o == nil || o.ValidTo == nil {
		var ret time.Time
		return ret
	}
	return *o.ValidTo
}

// GetValidToOk returns a tuple with the ValidTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetValidToOk() (*time.Time, bool) {
	if o == nil || o.ValidTo == nil {
		return nil, false
	}
	return o.ValidTo, true
}

// HasValidTo returns a boolean if a field has been set.
func (o *Source) HasValidTo() bool {
	if o != nil && o.ValidTo != nil {
		return true
	}

	return false
}

// SetValidTo gets a reference to the given time.Time and assigns it to the ValidTo field.
func (o *Source) SetValidTo(v time.Time) {
	o.ValidTo = &v
}

func (o Source) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.LastData != nil {
		toSerialize["last_data"] = o.LastData
	}
	if o.LastIngestChunkEndTime != nil {
		toSerialize["last_ingest_chunk_end_time"] = o.LastIngestChunkEndTime
	}
	if o.LastStoredChunkEndTime != nil {
		toSerialize["last_stored_chunk_end_time"] = o.LastStoredChunkEndTime
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.OrgUid != nil {
		toSerialize["org_uid"] = o.OrgUid
	}
	if o.ResourceName != nil {
		toSerialize["resource_name"] = o.ResourceName
	}
	if o.ResourcePolicy != nil {
		toSerialize["resource_policy"] = o.ResourcePolicy
	}
	if o.RuntimeDescription != nil {
		toSerialize["runtime_description"] = o.RuntimeDescription
	}
	if o.RuntimeDetails != nil {
		toSerialize["runtime_details"] = o.RuntimeDetails
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.ValidFrom != nil {
		toSerialize["valid_from"] = o.ValidFrom
	}
	if o.ValidTo != nil {
		toSerialize["valid_to"] = o.ValidTo
	}
	return json.Marshal(toSerialize)
}

type NullableSource struct {
	value *Source
	isSet bool
}

func (v NullableSource) Get() *Source {
	return v.value
}

func (v *NullableSource) Set(val *Source) {
	v.value = val
	v.isSet = true
}

func (v NullableSource) IsSet() bool {
	return v.isSet
}

func (v *NullableSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSource(val *Source) *NullableSource {
	return &NullableSource{value: val, isSet: true}
}

func (v NullableSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


